### ISSUE TITLE
North America Map Pieces

### ISSUE THREAD

**Issue by mwcrowther** [oxcug/team12#11]

**Comment by mwcrowther** [comment]
![northwest_territories](https://user-images.githubusercontent.com/47276435/52186667-21877e80-27e6-11e9-8681-021d1f88622f.png)
![ontario](https://user-images.githubusercontent.com/47276435/52186668-21877e80-27e6-11e9-9bc6-67f155f962d2.png)
![quebec](https://user-images.githubusercontent.com/47276435/52186669-21877e80-27e6-11e9-8baa-d294ba675699.png)
![western_us](https://user-images.githubusercontent.com/47276435/52186671-21877e80-27e6-11e9-974d-d3c0806ed5a1.png)
![alaska](https://user-images.githubusercontent.com/47276435/52186672-21877e80-27e6-11e9-8341-c3097dda2203.png)
![alberta](https://user-images.githubusercontent.com/47276435/52186673-21877e80-27e6-11e9-8559-abc438b56589.png)
![eastern_us](https://user-images.githubusercontent.com/47276435/52186674-22201500-27e6-11e9-84b2-6f02777f0a19.png)
![grennland](https://user-images.githubusercontent.com/47276435/52186675-22201500-27e6-11e9-8744-1040667cbd5c.png)
![mexico](https://user-images.githubusercontent.com/47276435/52186676-22201500-27e6-11e9-87e5-98e7616cfa41.png)

**Comment by oxcug** [comment]
@mwcrowther Nice work! I'm wondering if it might be easier to just trace over the states in photoshop or another vector drawing program? I think we'll need to crop them so they don't overlap in Unity. Also, they won't scale on larger / higher definition screens. Feel free to ignore me, these should will work fine after cropping :).

**Comment by mwcrowther** [comment]
I was kind of thinking the same thing. I did trace them all out using GIMP. I should have used cut instead of copy to make sure they will all fit back together. It just takes a lot of time. What scale are we thinking? I could double the scale, cut the pieces then invert them make a new boarder and texture? I can run some test with Australia.

**Comment by mwcrowther** [comment]
I went to double the image size, but it is already 3600X1800 if I double it the main map will be over 1.5 gigs

**Comment by mwcrowther** [comment]
![grennland-2](https://user-images.githubusercontent.com/47276435/52244893-b187ff80-289c-11e9-929d-57c6360f2196.png)

**Comment by mwcrowther** [comment]
![alaska2](https://user-images.githubusercontent.com/47276435/52244982-0461b700-289d-11e9-9e99-65b2e42d8b41.png)

**Comment by mwcrowther** [comment]
![alaska2](https://user-images.githubusercontent.com/47276435/52450705-6cacd480-2af9-11e9-890a-cc7cf6b6ebc1.png)

**Comment by mwcrowther** [comment]
![northwest2](https://user-images.githubusercontent.com/47276435/52451065-c3ff7480-2afa-11e9-8949-919fde7044c8.png)

**Comment by mwcrowther** [comment]
![alberta2](https://user-images.githubusercontent.com/47276435/52479903-65241480-2b67-11e9-9c40-3ba01bc5e9d3.png)

**Comment by mwcrowther** [comment]
![ontario2](https://user-images.githubusercontent.com/47276435/52481546-09a85580-2b6c-11e9-94e4-79c7252d3b49.png)

**Comment by mwcrowther** [comment]
![quebec2](https://user-images.githubusercontent.com/47276435/52481703-74599100-2b6c-11e9-947e-278965995bce.png)

**Comment by mwcrowther** [comment]
![westernus_2](https://user-images.githubusercontent.com/47276435/52481804-c8fd0c00-2b6c-11e9-97e4-7ce229364383.png)

**Comment by mwcrowther** [comment]
![easternus_2](https://user-images.githubusercontent.com/47276435/52481892-05306c80-2b6d-11e9-8bda-a246d78ef759.png)

**Comment by mwcrowther** [comment]
![mexico2](https://user-images.githubusercontent.com/47276435/52511400-fec9e100-2bbc-11e9-90c6-5ba308e7bd9e.png)

**Comment by mwcrowther** [comment]
![northamerica capture](https://user-images.githubusercontent.com/47276435/52511451-451f4000-2bbd-11e9-876e-a2773d4510a9.PNG)


In unity

**Comment by BDoyl** [comment]
That looks great.

**Comment by mwcrowther** [comment]
![greenland2](https://user-images.githubusercontent.com/47276435/52522625-fe752880-2c44-11e9-9ae0-501fab3716e6.png)
