### ISSUE TITLE
Africa Map Pieces

### ISSUE THREAD

**Issue by mwcrowther** [oxcug/team12#14]

**Comment by mwcrowther** [comment]
![egypt](https://user-images.githubusercontent.com/47276435/52246859-b355c100-28a4-11e9-92e2-e6a31040d824.png)
@oxcug 
This is the best way I have figured out yet. What do you think. I am up for easy ideas if you have any. Right now I am using a fuzzy select tool adding an interior border. They should all fit together, resolution is just a little low, but it will be a whole map

**Comment by mwcrowther** [comment]
I could try X1.5

**Comment by mwcrowther** [comment]
![egypt_1x5](https://user-images.githubusercontent.com/47276435/52250632-fcfad780-28b5-11e9-8c9b-333d05632f81.png)

**Comment by oxcug** [comment]
Looks good to me, I'll try to start working on gameplay tonight.
