### ISSUE TITLE
Default Map Design

### ISSUE THREAD

**Issue by oxcug** [oxcug/team12#4]
We need to figure out what our first map will look like!

**Comment by mwcrowther** [comment]
![world-domination-game-board-2-1-1](https://user-images.githubusercontent.com/47276435/52171183-89ba5f80-2715-11e9-948a-7d694ffc05b7.jpg)

**Comment by oxcug** [comment]
looks great to me. I think well just want the countries / land masses. well also need to split each state in the country up so they can be imported as separate game objects

**Comment by mwcrowther** [comment]
Starting to get some cut out. Might have to clean up the lettering in it has to be a larger scale
![northwest_territories](https://user-images.githubusercontent.com/47276435/52181641-4d3c4180-27b1-11e9-8933-61f32dcd46c2.png)

**Comment by oxcug** [comment]
Sounds good, it might be worth splitting out each country into it's own issue to make tracking easier.

**Comment by mwcrowther** [comment]
There are 42 I have completed 2 and got them in .png and tested that they drop into unity just fine. I will imagine we will need to recreate the map in unity and lock the pieces together into some type of board object.

**Comment by mwcrowther** [comment]
once I have them all split out I will copy the unity asset folder

**Comment by oxcug** [comment]
@mwcrowther Yep, in Unity, game objects under hierarchy respect their parents transforms as they move. Meaning, if you make an object a child of another, when you move the parent, you move the children as well. You can create "empty" game objects (transform only) to be a parent. You'll want to make an empty node for each country and each region in that country would be a child.

**Comment by oxcug** [comment]
@mwcrowther This issue can be closed, be sure to add the map to the repo (create a PR for review).

**Comment by mwcrowther** [comment]
Map is added
